name: Publish Turnstile demo to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'demo/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd demo
        echo "CLOUDFLARE_TURNSTILE_SITE_KEY=${{ secrets.CLOUDFLARE_TURNSTILE_SITE_KEY }}" >> .env
        echo "CLOUDFLARE_TURNSTILE_SECRET_KEY=${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}" >> .env
        export CLOUDFLARE_TURNSTILE_SITE_KEY=${{ secrets.CLOUDFLARE_TURNSTILE_SITE_KEY }}
        export CLOUDFLARE_TURNSTILE_SECRET_KEY=${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}
        npm ci
        cd ..
        npm ci
        npm run build
        cd demo
        npm ci
        source .env
        cat .env
        npm run build

    - name: Publish to Cloudflare Pages
      uses: sctg-development/pages-action-without-url@main
      with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: turnstile-demo
            directory: dist
            workingDirectory: demo
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
            wranglerVersion: '4'